// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaj_KRF-P3sAgGU6leLBwjoJXT9wraQJ0',
    appId: '1:789991296498:web:833470f30bc48551452f6b',
    messagingSenderId: '789991296498',
    projectId: 'my-shoe-store-a24d6',
    authDomain: 'my-shoe-store-a24d6.firebaseapp.com',
    storageBucket: 'my-shoe-store-a24d6.firebasestorage.app',
    measurementId: 'G-2V2Y4P7QSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiU6GD32dBDNwFi1ojoJL0XtcpCITxCwE',
    appId: '1:789991296498:android:e59e3051aa17829f452f6b',
    messagingSenderId: '789991296498',
    projectId: 'my-shoe-store-a24d6',
    storageBucket: 'my-shoe-store-a24d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGHuaDpyv3hXhIUPULO2kw-pyCFM562AE',
    appId: '1:789991296498:ios:0e446eecf1c9672e452f6b',
    messagingSenderId: '789991296498',
    projectId: 'my-shoe-store-a24d6',
    storageBucket: 'my-shoe-store-a24d6.firebasestorage.app',
    iosBundleId: 'com.example.shoeStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGHuaDpyv3hXhIUPULO2kw-pyCFM562AE',
    appId: '1:789991296498:ios:0e446eecf1c9672e452f6b',
    messagingSenderId: '789991296498',
    projectId: 'my-shoe-store-a24d6',
    storageBucket: 'my-shoe-store-a24d6.firebasestorage.app',
    iosBundleId: 'com.example.shoeStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaj_KRF-P3sAgGU6leLBwjoJXT9wraQJ0',
    appId: '1:789991296498:web:bb927a00f148616c452f6b',
    messagingSenderId: '789991296498',
    projectId: 'my-shoe-store-a24d6',
    authDomain: 'my-shoe-store-a24d6.firebaseapp.com',
    storageBucket: 'my-shoe-store-a24d6.firebasestorage.app',
    measurementId: 'G-1W98FS08CN',
  );
}
